#services:
#  postgres:
#    container_name: postgres_container
#    image: postgres:14
#    environment:
#      POSTGRES_USER: techlearning
#      POSTGRES_PASSWORD: techlearning
#      PGDATA: /c/data/postgres
#    volumes:
#      - postgres:/c/data/postgres
#    ports:
#      - "5432:5432"
#    restart: unless-stopped
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/c/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: unless-stopped


#FROM openjdk:22-oracle
#COPY