server:
  port: 8080

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: https://localhost:8082
          predicates:
            - Path=/api/user/**
        - id: product-service
          uri: https://localhost:8083
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: https://localhost:8084
          predicates:
            - Path=/api/orders/**,/api/cart/**
