spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888

###################################
#  datasource:
#    url: jdbc:postgresql://localhost:5432/mydb
#    username: techlearning
#    password: techlearning
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#
#  jpa:
##    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgeSQLDialect


