spring:
    application:
        name: order-service
    config:
        import: optional:configserver:http://localhost:8888


#server:
#    port: 8084
#
#spring:
#    application:
#        name: Order
##    datasource:
##        url: jdbc:postgresql://172.17.0.2:5432/mydb
##        username: techlearning
##        password: techlearning
#    h2:
#        console:
#            enabled: true
#    datasource:
#        url: jdbc:h2:mem:test
#
#    jpa:
##        database: POSTGRESQL
#        show-sql: true
#        hibernate:
#            ddl-auto: create
##        database-platform: org.hibernate.dialect.PostgreSQLDialect
