server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/techlearning
    username: root
    password: root
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test

  jpa:
    #    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database-platform: org.hibernate.dialect.PostgeSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rolling-policy:
      max-file-size: 5MB
      max-history: 7    #days