server:
  port: 8082

spring:
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/mydb
  #    username: techlearning
  #    password: techlearning
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    #    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgeSQLDialect

#  spring.application.name=order-service
#  spring.h2.console.enabled = true
#  spring.datasource.url = jdbc:h2:mem:test
#  spring.jpa.show-sql=true
#  spring.jpa.hibernate.ddl-auto=create


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7    #days